from __future__ import annotations

from copy import deepcopy


def get_fake_database() -> dict[str, object]:
    """Return an in-memory demo database used by the ROUH web MVC app."""
    return deepcopy(
        {
            "app": {
                "name": "ROUH",
                "tagline": "Votre sante, notre priorite",
                "support": "support@rouh.ma",
                "city": "Casablanca",
            },
            "accounts": [
                {
                    "id": "ADM-001",
                    "role": "admin",
                    "role_label": "Administrateur",
                    "name": "Admin Rouh",
                    "email": "admin@rouh.ma",
                    "phone": "06 10 00 00 01",
                    "password": "admin123",
                    "city": "Casablanca",
                    "status": "Actif",
                    "title": "Super Administrateur",
                    "avatar": "AR",
                },
                {
                    "id": "PAT-100",
                    "role": "patient",
                    "role_label": "Patient",
                    "name": "Ahmed Benali",
                    "email": "ahmed.benali@rouh.ma",
                    "phone": "06 12 34 56 78",
                    "password": "patient123",
                    "city": "Casablanca",
                    "status": "Actif",
                    "title": "Patient",
                    "avatar": "AB",
                },
                {
                    "id": "PAT-101",
                    "role": "patient",
                    "role_label": "Patient",
                    "name": "Fatima Zahra",
                    "email": "fatima.zahra@rouh.ma",
                    "phone": "06 23 45 67 89",
                    "password": "demo123",
                    "city": "Casablanca",
                    "status": "Actif",
                    "title": "Patient",
                    "avatar": "FZ",
                },
                {
                    "id": "DOC-200",
                    "role": "doctor",
                    "role_label": "Medecin",
                    "name": "Dr Karim Benali",
                    "email": "karim.benali@rouh.ma",
                    "phone": "06 22 44 66 88",
                    "password": "doctor123",
                    "city": "Casablanca",
                    "status": "Verifie",
                    "title": "Cardiologue",
                    "specialty": "Cardiologie",
                    "avatar": "KB",
                },
                {
                    "id": "DOC-201",
                    "role": "doctor",
                    "role_label": "Medecin",
                    "name": "Dr Sara El Amrani",
                    "email": "sara.elamrani@rouh.ma",
                    "phone": "06 78 90 90 00",
                    "password": "demo123",
                    "city": "Rabat",
                    "status": "Actif",
                    "title": "Generaliste",
                    "specialty": "Generaliste",
                    "avatar": "DS",
                },
                {
                    "id": "DOC-202",
                    "role": "doctor",
                    "role_label": "Medecin",
                    "name": "Dr Youssef Amine",
                    "email": "youssef.amine@rouh.ma",
                    "phone": "06 77 88 99 00",
                    "password": "demo123",
                    "city": "Marrakech",
                    "status": "Actif",
                    "title": "Pediatre",
                    "specialty": "Pediatrie",
                    "avatar": "YA",
                },
                {
                    "id": "NUR-300",
                    "role": "nurse",
                    "role_label": "Infirmier",
                    "name": "Infirmiere Fatima Zahra",
                    "email": "fatima.zahra@rouh.ma",
                    "phone": "06 32 21 10 00",
                    "password": "nurse123",
                    "city": "Casablanca",
                    "status": "Actif",
                    "title": "Soins infirmiers",
                    "specialty": "Soins infirmiers",
                    "avatar": "FZ",
                },
                {
                    "id": "NUR-301",
                    "role": "nurse",
                    "role_label": "Infirmier",
                    "name": "Infirmier Ahmed",
                    "email": "ahmed.infirmier@rouh.ma",
                    "phone": "06 11 22 33 44",
                    "password": "demo123",
                    "city": "Casablanca",
                    "status": "Actif",
                    "title": "Soins post-operatoires",
                    "specialty": "Soins post-operatoires",
                    "avatar": "IA",
                },
                {
                    "id": "PHA-400",
                    "role": "pharmacy",
                    "role_label": "Pharmacie",
                    "name": "Pharmacie Centrale",
                    "email": "contact@pharmaciecentrale.ma",
                    "phone": "05 22 33 44 55",
                    "password": "pharmacy123",
                    "city": "Casablanca",
                    "status": "Actif",
                    "title": "Pharmacien",
                    "avatar": "PC",
                },
                {
                    "id": "PHA-401",
                    "role": "pharmacy",
                    "role_label": "Pharmacie",
                    "name": "Pharmacie Al Amal",
                    "email": "contact@pharmaciealamal.ma",
                    "phone": "05 37 62 11 22",
                    "password": "demo123",
                    "city": "Rabat",
                    "status": "Actif",
                    "title": "Pharmacien",
                    "avatar": "PA",
                },
                {
                    "id": "URG-500",
                    "role": "emergency",
                    "role_label": "Urgence",
                    "name": "Urgence Admin",
                    "email": "urgence.admin@rouh.ma",
                    "phone": "06 12 34 56 78",
                    "password": "emergency123",
                    "city": "Casablanca",
                    "status": "Actif",
                    "title": "Responsable des urgences",
                    "avatar": "UA",
                },
            ],
            "registration_requests": [
                {
                    "id": "REQ-2401",
                    "name": "Dr Youssef Amine",
                    "role": "Medecin",
                    "email": "youssef.amine@example.com",
                    "phone": "06 77 88 99 00",
                    "date": "31 Mai 2024 - 11:10",
                    "status": "En attente",
                },
                {
                    "id": "REQ-2402",
                    "name": "Infirmiere Sarah",
                    "role": "Infirmier",
                    "email": "sarah.infirmiere@example.com",
                    "phone": "06 23 45 67 89",
                    "date": "31 Mai 2024 - 13:45",
                    "status": "En attente",
                },
                {
                    "id": "REQ-2403",
                    "name": "Pharmacie Noor",
                    "role": "Pharmacie",
                    "email": "contact@pharmacienoor.ma",
                    "phone": "05 28 18 10 20",
                    "date": "31 Mai 2024 - 12:20",
                    "status": "En attente",
                },
            ],
            "doctors": [
                {"id": "DOC-200", "name": "Dr Karim Benali", "specialty": "Cardiologie", "phone": "06 22 44 66 88", "status": "Actif", "experience": "8 ans", "rating": "4.8"},
                {"id": "DOC-201", "name": "Dr Sara El Amrani", "specialty": "Generaliste", "phone": "06 78 90 90 00", "status": "Actif", "experience": "7 ans", "rating": "4.7"},
                {"id": "DOC-202", "name": "Dr Youssef Amine", "specialty": "Pediatrie", "phone": "06 77 88 99 00", "status": "Actif", "experience": "10 ans", "rating": "4.9"},
                {"id": "DOC-203", "name": "Dr Fatima Zahra", "specialty": "Dermatologie", "phone": "06 23 45 67 89", "status": "Actif", "experience": "6 ans", "rating": "4.8"},
                {"id": "DOC-204", "name": "Dr Mehdi Alami", "specialty": "Neurologie", "phone": "06 45 12 78 90", "status": "Actif", "experience": "12 ans", "rating": "4.8"},
                {"id": "DOC-205", "name": "Dr Amina Hassan", "specialty": "Gynecologie", "phone": "06 55 66 77 88", "status": "Actif", "experience": "9 ans", "rating": "4.6"},
            ],
            "patients": [
                {"id": "PAT-100", "name": "Ahmed Benali", "email": "ahmed.benali@rouh.ma", "phone": "06 12 34 56 78", "age": 34, "room": "102", "doctor": "Dr Karim Benali", "status": "Stable"},
                {"id": "PAT-101", "name": "Fatima Zahra", "email": "fatima@example.com", "phone": "06 23 45 67 89", "age": 28, "room": "105", "doctor": "Dr Karim Benali", "status": "Stable"},
                {"id": "PAT-102", "name": "Youssef Mohamed", "email": "youssef@example.com", "phone": "06 11 22 33 44", "age": 42, "room": "103", "doctor": "Dr Karim Benali", "status": "Sous surveillance"},
                {"id": "PAT-103", "name": "Amina Hassan", "email": "amina@example.com", "phone": "06 55 66 77 88", "age": 37, "room": "107", "doctor": "Dr Karim Benali", "status": "Stable"},
            ],
            "nurses": [
                {"id": "NUR-300", "name": "Infirmiere Fatima Zahra", "specialty": "Soins infirmiers", "phone": "06 32 21 10 00", "status": "Actif"},
                {"id": "NUR-301", "name": "Infirmier Ahmed", "specialty": "Soins post-operatoires", "phone": "06 11 22 33 44", "status": "Actif"},
                {"id": "NUR-302", "name": "Infirmiere Amina", "specialty": "Soins aux personnes agees", "phone": "06 33 22 11 00", "status": "Actif"},
                {"id": "NUR-303", "name": "Infirmiere Sarah", "specialty": "Soins chroniques", "phone": "06 24 57 68 90", "status": "Actif"},
                {"id": "NUR-304", "name": "Infirmier Hassan", "specialty": "Soins d'urgence", "phone": "06 44 56 67 78", "status": "Actif"},
            ],
            "pharmacies": [
                {"id": "PHA-400", "name": "Pharmacie Centrale", "address": "123 Bd Mohammed V, Casablanca", "phone": "05 22 33 44 55", "status": "Active"},
                {"id": "PHA-401", "name": "Pharmacie Al Amal", "address": "45 Avenue Hassan II, Rabat", "phone": "05 37 62 11 22", "status": "Active"},
                {"id": "PHA-402", "name": "Pharmacie Les Oliviers", "address": "12 Rue des Oliviers, Marrakech", "phone": "05 24 33 44 66", "status": "Active"},
                {"id": "PHA-403", "name": "Pharmacie Ibn Sina", "address": "78 Boulevard Zerktouni, Casablanca", "phone": "05 22 18 10 20", "status": "Active"},
            ],
            "appointments": [
                {"id": "RDV-001", "patient": "Ahmed Benali", "doctor": "Dr Karim Benali", "date": "22 Mai 2024 - 10:30", "type": "Teleconsultation", "reason": "Suivi hypertension", "status": "Confirme"},
                {"id": "RDV-002", "patient": "Fatima Zahra", "doctor": "Dr Karim Benali", "date": "22 Mai 2024 - 14:00", "type": "Cabinet", "reason": "Controle general", "status": "En attente"},
                {"id": "RDV-003", "patient": "Youssef Mohamed", "doctor": "Dr Sara El Amrani", "date": "23 Mai 2024 - 15:00", "type": "Teleconsultation", "reason": "Resultats analyses", "status": "Confirme"},
                {"id": "RDV-004", "patient": "Ahmed Benali", "doctor": "Dr Sara El Amrani", "date": "24 Mai 2024 - 09:30", "type": "Cabinet", "reason": "Douleur thoracique", "status": "En attente"},
                {"id": "RDV-005", "patient": "Ahmed Benali", "doctor": "Dr Youssef Amine", "date": "05 Juin 2024 - 11:00", "type": "Teleconsultation", "reason": "Controle", "status": "Confirme"},
            ],
            "medications": [
                {"id": "MED-001", "patient": "Ahmed Benali", "name": "Atorvastatine", "dosage": "20 mg", "frequency": "1 comprime / jour", "next": "08:00", "status": "En cours"},
                {"id": "MED-002", "patient": "Ahmed Benali", "name": "Amlodipine", "dosage": "5 mg", "frequency": "1 comprime / jour", "next": "20:00", "status": "En cours"},
                {"id": "MED-003", "patient": "Fatima Zahra", "name": "Paracetamol", "dosage": "1 g", "frequency": "si douleur", "next": "09:00", "status": "A administrer"},
            ],
            "prescriptions": [
                {"id": "ORD-100", "patient": "Ahmed Benali", "doctor": "Dr Karim Benali", "status": "A traiter", "total": "245 DH", "date": "22 Mai 2024 - 10:30"},
                {"id": "ORD-101", "patient": "Fatima Zahra", "doctor": "Dr Amina Hassan", "status": "En preparation", "total": "167 DH", "date": "22 Mai 2024 - 10:15"},
                {"id": "ORD-102", "patient": "Sara Benkirane", "doctor": "Dr Karim Benali", "status": "Prete", "total": "156 DH", "date": "22 Mai 2024 - 09:10"},
            ],
            "home_care": [
                {"id": "CARE-001", "patient": "Ahmed Benali", "nurse": "Infirmiere Fatima Zahra", "care": "Prise de tension", "date": "22 Mai 2024 - 08:00", "priority": "Normale", "status": "A faire"},
                {"id": "CARE-002", "patient": "Fatima Zahra", "nurse": "Infirmier Ahmed", "care": "Pansement", "date": "22 Mai 2024 - 09:00", "priority": "Normale", "status": "A faire"},
                {"id": "CARE-003", "patient": "Youssef Mohamed", "nurse": "Infirmiere Fatima Zahra", "care": "Injection", "date": "22 Mai 2024 - 10:00", "priority": "Elevee", "status": "En cours"},
                {"id": "CARE-004", "patient": "Amina Hassan", "nurse": "Infirmiere Fatima Zahra", "care": "Surveillance", "date": "22 Mai 2024 - 11:00", "priority": "Normale", "status": "A faire"},
                {"id": "CARE-005", "patient": "Mohamed Ali", "nurse": "Infirmiere Fatima Zahra", "care": "Soins d'hygiene", "date": "22 Mai 2024 - 12:00", "priority": "Normale", "status": "Realise"},
                {"id": "CARE-006", "patient": "Sara Benkirane", "nurse": "Infirmiere Fatima Zahra", "care": "Prise de glycemie", "date": "22 Mai 2024 - 14:00", "priority": "Normale", "status": "A faire"},
            ],
            "emergencies": [
                {"id": "SOS-001", "patient": "Ahmed Benali", "type": "Accident de la route", "location": "Avenue Hassan II, Casablanca", "gravity": "Critique", "status": "Nouveau", "team": "Equipe 2", "time": "14:28"},
                {"id": "SOS-002", "patient": "Fatima Zahra", "type": "Malaise cardiaque", "location": "Hay Riad, Rabat", "gravity": "Critique", "status": "Assigne", "team": "Equipe 1", "time": "13:45"},
                {"id": "SOS-003", "patient": "Youssef Mohamed", "type": "Chute", "location": "Gueliz, Marrakech", "gravity": "Elevee", "status": "En cours", "team": "Equipe 3", "time": "13:10"},
            ],
            "pharmacy_stock": [
                {"name": "Paracetamol 1g", "category": "Antalgiques", "stock": 12, "price": "2,50 DH", "status": "Stock faible"},
                {"name": "Amoxicilline 1g", "category": "Antibiotiques", "stock": 0, "price": "12,00 DH", "status": "Rupture de stock"},
                {"name": "Ibuprofene 400mg", "category": "Antalgiques", "stock": 45, "price": "3,20 DH", "status": "En stock"},
                {"name": "Amlodipine 5mg", "category": "Cardiologie", "stock": 80, "price": "7,10 DH", "status": "En stock"},
            ],
            "messages": [
            ],
            "activities": [
                {"title": "Nouveau patient inscrit", "type": "Patient", "time": "Il y a 2 min"},
                {"title": "Demande de rendez-vous", "type": "Rendez-vous", "time": "Il y a 5 min"},
                {"title": "Nouvelle commande", "type": "Commande", "time": "Il y a 8 min"},
                {"title": "Alerte SOS declenchee", "type": "Urgence", "time": "Il y a 12 min"},
                {"title": "Ordonnance consultee", "type": "Pharmacie", "time": "Il y a 18 min"},
                {"title": "Soin a domicile accepte", "type": "Infirmier", "time": "Il y a 24 min"},
            ],
            "history": [
                {"date": "08 Mai 2026 - 00:54", "actor": "Systeme", "event": "Base demo initialisee", "status": "Archive"},
                {"date": "08 Mai 2026 - 00:55", "actor": "Admin Rouh", "event": "Consultation utilisateurs", "status": "Archive"},
                {"date": "08 Mai 2026 - 00:57", "actor": "Ahmed Benali", "event": "Demande de rendez-vous envoyee", "status": "Archive"},
                {"date": "08 Mai 2026 - 01:02", "actor": "Pharmacie Centrale", "event": "Commande mise en preparation", "status": "Archive"},
            ],
        }
    )
